### ISSUE TITLE
Image Size!!

### ISSUE THREAD

**Issue by Nitroito** [the-sh4d0w/too-cheap#1]
game crashes!! the crash report cant identify the callstack but i am SURE it crashes because of this MOD... i remove the mod and no more game crash!

PS: why is the file "/assets/too-cheap/too-cheap-background.png" have a file size of 5.3MB???
weird!!

**Comment by the-sh4d0w** [comment]
Thank you for opening this issue.

If you could please share the following information to help me solve this issue:
- crash log
- game version
- mod version
- when the game crashes specifically
- are you using any other mods that affect the anvil?

Regarding the large file: that is a screenshot I'm using for the modrinth page banner. It is indeed weird that past me decided to put that in the jar file, I'm going to remove that in the next version.
