### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by Proxi2** [the-sh4d0w/too-cheap#3]
No rush, I know the version just came out. Just a nudge. It's been a godsend on my server in 1.20.6 and I'd be honored to have it in the server for 1.21 :)

**Comment by the-sh4d0w** [comment]
[Done.](https://modrinth.com/mod/too-cheap/version/1.3.0+mc1.21)

**Comment by the-sh4d0w** [comment]
[Done.](https://modrinth.com/mod/too-cheap/version/1.3.0+mc1.21)
