### ISSUE TITLE
1.21.3 [Bundles of Bravery] Port

### ISSUE THREAD

**Issue by SilasExperiment** [the-sh4d0w/too-cheap#4]
Wondering if this could get a 1.21.3 port? Don't feel pressured to make this quickly, and thanks for making this mod to begin with!

**Comment by the-sh4d0w** [comment]
[Done.](https://modrinth.com/mod/too-cheap/version/1.4.0+mc1.21.2)

**Comment by the-sh4d0w** [comment]
[Done.](https://modrinth.com/mod/too-cheap/version/1.4.0+mc1.21.2)
